server:
  port: 8080
spring:
  application:
    name: reggie_take_out
#  datasource:
#    druid:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/db_reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      username: root
#      password: root
  main:
    allow-bean-definition-overriding: true
  shardingsphere:
    datasource:
      names:
        master,slave
        # 主数据源
      master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.40.129:3306/db_reggie?characterEncoding=utf-8
        username: xiaoming
        password: 123456
        # 从数据源
      slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://192.168.40.131:3306/db_reggie?characterEncoding=utf-8
        username: xiaoming
        password: 123456
    masterslave:
        # 读写分离配置
      load-balance-algorithm-type: round_robin
        # 最终的数据源名称
      name: dataSource
        # 主库数据源名称
      master-data-source-name: master
        # 从库数据源名称列表，多个逗号分隔
      slave-data-source-names: slave
    props:
        # 开启SQL显示，默认false
      sql:
        show: true
  redis:
    host: 192.168.40.129
    port: 6379
    password: root@123456
    database: 0
  cache:
    redis:
      time-to-live: 1800000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
reggie:
  path: D:\img\